# Generated by Django 4.2.11 on 2024-03-31 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_alter_hotel_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='visit_status',
            field=models.CharField(choices=[('I_was_there', 'I was there'), ('I_want_to_go', 'I want to go'), ('Never_went', 'Never went'), ('Wishing_but_broke', 'Wishing but broke')], default='I was there', max_length=20),
        ),
    ]
