# Generated by Django 4.2.11 on 2024-04-08 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotels', '0005_hotelphoto_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_hotels', to=settings.AUTH_USER_MODEL),
        ),
    ]
