# Generated by Django 4.2.11 on 2024-04-08 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_hotel_added_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='added_by',
            new_name='owner',
        ),
    ]
