# Generated by Django 4.2.11 on 2024-04-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_rename_added_by_hotel_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(),
        ),
    ]
