# Generated by Django 4.2.11 on 2024-03-31 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotels', '0003_alter_hotel_location'),
        ('common', '0003_alter_hotelcomment_hotel_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelcomment',
            name='hotel_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='hotels.hotelphoto'),
        ),
        migrations.AlterField(
            model_name='hotelcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hotellike',
            name='hotel_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='hotels.hotelphoto'),
        ),
        migrations.AlterField(
            model_name='hotellike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
